### PR TITLE
Feature/homepage: welcoming message - no lists on sidebar added

### PR DESCRIPTION
**Pull request by maysunktong**
Added capybara favicon as well.
You will unfortunately see this preview on `development`
So please code review.

### CODE REVIEW

**Review by mvic89 — APPROVED** [review]
Cute favicons! :)

Looks good from my part.

**Review by Endorze — CHANGES_REQUESTED** [review]
Any styling that is not used on all html pages should not be there, i notice you put your page styling into the global CSS, this should be in for example "mammals.css" / "reptiles.css" etc.

Move this into your own CSS file and resubmit 🙏 😄

**Comment by maysunktong** [comment]
@Endorze the requested change is done. Separated css file for landing-page. Please take a look

**Review by Endorze — APPROVED** [review]
Looks good! 😄

**Pull request merged**
