### PR TITLE
Feature/homepage-Animal Card Build (css and js)

### PR DESCRIPTION
**Pull request by maysunktong**
I successfully brought back my JS code for you to review (sweaty 😅)

Requirements:
Sidebar -Shows a list with the names of all the animals​
Welcoming page is a default window.
Each animal on sidebar can be clicked to activate and deactivate to display a short summary modal. 

Short summary (top to bottom)
- group (link to each group page)
- name
- food
- the first 200 characters of the description

🔎 To tester:
- Test the whole functionality of Homepage and its responsiveness
- Please test a new sidebar toggle too and give feedback on Miro. 🙏🏻
image

### CODE REVIEW

**Review by Bor-ghol — COMMENTED** [review]
I love the design and the functionlity with the cards and all. 
But is it the short summary supposed to be like this ? 
Capture d'écran 2024-12-07 131617
Capture d'écran 2024-12-07 131643

**Review by Endorze — APPROVED** [review]
Lgtm 😄

**Comment by maysunktong** [comment]
@Bor-ghol I am not sure where you get the preview from. So far I have not merged this into development. 
You could code review on this one and then you can see my latest change on Vercel there and test. :)

**Review by mvic89 — APPROVED** [review]
Looks good!

**Pull request merged**
