### PR TITLE
added the responsiveness for mobile and tablet as well as fixed modal…

### PR DESCRIPTION
**Pull request by Bor-ghol**
Hello! 
I added responsivenss for the page for both tablet, laptop & mobile. 
I also fixed html code and added a part for modal because the read more button was not working for me. 
Please review my code and test it throughly.

### CODE REVIEW

**Comment by bosilf** [comment]
could you please post screen shots on how you page looks for you in the different screen sizes (iphone 12 pro, ipad mini, and desktop) with the sidebar open? It looks like this for me: 
Screenshot 2024-12-08 at 18 34 15
Screenshot 2024-12-08 at 18 34 27
Screenshot 2024-12-08 at 18 34 39

**Review by bosilf — APPROVED** [review]
I'll look at it in development

**Comment by Bor-ghol** [comment]
Hello! 
I made some modification on my responsiveness and I believe it should be fully responsive now. 
I will pull it to dev after approval of code 
Capture d'écran 2024-12-08 201224
Capture d'écran 2024-12-08 201203

**Review by maysunktong — APPROVED** [review]
Modal looks really cool. Responsiveness is good!

**Pull request merged**
